/*
 * 
 * 
 * 4. You are given two strings s and t.
‌
String t is generated by random shuffling string s and then add one more letter at a random position.
‌
Return the letter that was added to t.
‌
Example 1:
Input: s = "abcd", t = "abcde"
Output: "e"
Explanation: 'e' is the letter that was added.
‌
Example 2:
Input: s = "", t = "y"
Output: "y"
‌
Constraints:
0 <= s.length <= 1000
t.length == s.length + 1
s and t consist of lowercase English letters.
 * 
 * 
 */

import java.util.Scanner;

public class Task4 {
    public static void main(String[] args) {
        Scanner sc = new Scanner(System.in);

        System.out.print("Enter the String 1 : ");
        String s = sc.nextLine(); // get input from the user // get input from the user 

        System.out.print("Enter the String 2 : ");
        String t = sc.nextLine(); // get input from the user 

        System.out.println(findAddedChar(s,t)); // this will print the added char 
    }

    // this method will find the added character
    public static char  findAddedChar(String s , String t){
        int result =0;
        for(char c : s.toCharArray()) result = result ^ c;
        for(char c : t.toCharArray()) result = result ^ c;
        return (char) result;
    }
}
